[project]
name = "kanta-lab-preprocessing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.6",
    "pandas>=3.0.2",
    "polars>=1.40.0",
    "pyarrow>=24.0.0",
    "tqdm>=4.70.0",
]

[dependency-groups]
dev = [
    "ipython>=9.12.0",
    "pytest>=9.0.3",
    "ruff>=0.15.10",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"

[tool.uv]
required-version = ">=0.9.17"
exclude-newer = "14 days"

[tool.uv.build-backend]
module-name = "kanta"
