SELECT
    FINNGENID,
    SEX,
    EVENT_AGE,
    APPROX_EVENT_DATETIME,
    `cleaned::TEST_NAME_ABBREVIATION` AS TEST_NAME,
    TEST_ID,
    TEST_ID_IS_NATIONAL,
    multiIf(`harmonization_omop::OMOP_ID` = '-1', 'NA', `harmonization_omop::OMOP_ID` = '0', 'NA', `harmonization_omop::OMOP_ID`) AS OMOP_CONCEPT_ID,
    `cleaned::MEASUREMENT_VALUE` AS MEASUREMENT_VALUE,
    `cleaned::MEASUREMENT_UNIT` AS MEASUREMENT_UNIT,
    `harmonization_omop::MEASUREMENT_VALUE` AS MEASUREMENT_VALUE_HARMONIZED,
    `harmonization_omop::MEASUREMENT_UNIT` AS MEASUREMENT_UNIT_HARMONIZED,
    TEST_OUTCOME,
    `imputed::TEST_OUTCOME` AS TEST_OUTCOME_IMPUTED,
    MEASUREMENT_STATUS,
    REFERENCE_RANGE_GROUP,
    REFERENCE_RANGE_LOWER_VALUE AS REFERENCE_RANGE_LOW_VALUE,
    REFERENCE_RANGE_LOWER_UNIT AS REFERENCE_RANGE_LOW_UNIT,
    REFERENCE_RANGE_UPPER_VALUE AS REFERENCE_RANGE_HIGH_VALUE,
    REFERENCE_RANGE_UPPER_UNIT AS REFERENCE_RANGE_HIGH_UNIT,
    kanta_lab_table.CODING_SYSTEM_MAP AS CODING_SYSTEM_ORG,
    kanta_lab_table.CODING_SYSTEM AS CODING_SYSTEM_OID
FROM file({filePathMungedTxtGz:String}, TSVWithNames) kanta_lab_table

-- Sorting using all columns to make the output deterministic.
ORDER BY (
    FINNGENID,
    SEX,
    APPROX_EVENT_DATETIME,
    EVENT_AGE,
    OMOP_CONCEPT_ID,
    TEST_NAME,
    TEST_ID,
    TEST_ID_IS_NATIONAL,
    MEASUREMENT_STATUS,
    TEST_OUTCOME,
    TEST_OUTCOME_IMPUTED,
    MEASUREMENT_VALUE,
    MEASUREMENT_UNIT,
    MEASUREMENT_VALUE_HARMONIZED,
    MEASUREMENT_UNIT_HARMONIZED,
    REFERENCE_RANGE_GROUP,
    REFERENCE_RANGE_LOW_VALUE,
    REFERENCE_RANGE_LOW_UNIT,
    REFERENCE_RANGE_HIGH_VALUE,
    REFERENCE_RANGE_HIGH_UNIT,
    CODING_SYSTEM_OID,
    CODING_SYSTEM_ORG
)

-- Deduplicating rows.
LIMIT 1 BY (
    FINNGENID,
    SEX,
    APPROX_EVENT_DATETIME,
    EVENT_AGE,
    OMOP_CONCEPT_ID,
    TEST_NAME,
    TEST_ID,
    TEST_ID_IS_NATIONAL,
    MEASUREMENT_STATUS,
    TEST_OUTCOME,
    TEST_OUTCOME_IMPUTED,
    MEASUREMENT_VALUE,
    MEASUREMENT_UNIT,
    MEASUREMENT_VALUE_HARMONIZED,
    MEASUREMENT_UNIT_HARMONIZED,
    REFERENCE_RANGE_GROUP,
    REFERENCE_RANGE_LOW_VALUE,
    REFERENCE_RANGE_LOW_UNIT,
    REFERENCE_RANGE_HIGH_VALUE,
    REFERENCE_RANGE_HIGH_UNIT,
    CODING_SYSTEM_OID,
    CODING_SYSTEM_ORG
)

-- Set output format to TSV-gzipped with a header.
FORMAT TSVWithNames

-- Disable data type inference from TSV text file.
SETTINGS input_format_tsv_use_best_effort_in_schema_inference = 0
