SELECT
  FINNGENID,
  SEX,
  EVENT_AGE :: Float64 AS EVENT_AGE,
  concat(APPROX_EVENT_DATETIME, ':00') :: DateTime64(3, 'UTC') AS APPROX_EVENT_DATETIME,
  TEST_NAME,
  TEST_ID,
  TEST_ID_IS_NATIONAL :: Bool AS TEST_ID_IS_NATIONAL,
  nullIf(OMOP_CONCEPT_ID, 'NA') :: Nullable(String) AS OMOP_CONCEPT_ID,
  nullIf(MEASUREMENT_VALUE_HARMONIZED, 'NA') :: Nullable(Float64) AS MEASUREMENT_VALUE_HARMONIZED,
  nullIf(MEASUREMENT_UNIT_HARMONIZED, 'NA') :: Nullable(String) AS MEASUREMENT_UNIT_HARMONIZED,
  nullIf(TEST_OUTCOME_MERGED, 'NA') :: Nullable(String) AS TEST_OUTCOME_MERGED,
  nullIf(TEST_OUTCOME_SOURCE, 'NA') :: Nullable(String) AS TEST_OUTCOME_SOURCE,
  nullIf(MEASUREMENT_STATUS, 'NA') :: Nullable(String) AS MEASUREMENT_STATUS,
  nullIf(MEASUREMENT_VALUE_EXTRACTED, 'NA') :: Nullable(Float64) AS MEASUREMENT_VALUE_EXTRACTED,
  IS_VALUE_EXTRACTED AS IS_VALUE_EXTRACTED,
  nullIf(OUTCOME_POS_EXTRACTED, 'NA') :: Nullable(Int8) AS OUTCOME_POS_EXTRACTED,
  nullIf(OUTCOME_TEXT_EXTRACTED, 'NA') :: Nullable(String) AS OUTCOME_TEXT_EXTRACTED

  FROM file({filePathCleanTxtGz:String}, TSVWithNames)
	 

-- Make the output deterministic by using ORDER BY on all columns
 ORDER BY (
   FINNGENID,
   SEX,
   APPROX_EVENT_DATETIME,
   EVENT_AGE,
   OMOP_CONCEPT_ID,
   TEST_NAME,
   TEST_ID,
   TEST_ID_IS_NATIONAL,
   MEASUREMENT_STATUS,
   TEST_OUTCOME_MERGED,
   TEST_OUTCOME_SOURCE,
   MEASUREMENT_VALUE_HARMONIZED,
   MEASUREMENT_UNIT_HARMONIZED,
   MEASUREMENT_VALUE_EXTRACTED,
   IS_VALUE_EXTRACTED,
   OUTCOME_POS_EXTRACTED,
   OUTCOME_TEXT_EXTRACTED
)

FORMAT Parquet
SETTINGS
    input_format_tsv_use_best_effort_in_schema_inference = 0,
    output_format_parquet_compression_method = 'zstd',
    output_format_parquet_string_as_string = 1
