SELECT
  FINNGENID,
  SEX,
  EVENT_AGE,
  APPROX_EVENT_DATETIME,
  `cleaned::TEST_NAME_ABBREVIATION` AS TEST_NAME,
  TEST_ID,
  TEST_ID_IS_NATIONAL,
  multiIf(`harmonization_omop::OMOP_ID` = '-1', 'NA', `harmonization_omop::OMOP_ID` = '0', 'NA', `harmonization_omop::OMOP_ID`) AS OMOP_CONCEPT_ID,
  `harmonization_omop::MEASUREMENT_VALUE` AS MEASUREMENT_VALUE_HARMONIZED,
  `harmonization_omop::MEASUREMENT_UNIT` AS MEASUREMENT_UNIT_HARMONIZED,
  `merged::TEST_OUTCOME` AS TEST_OUTCOME_MERGED,
  `merged::OUTCOME_SOURCE` AS TEST_OUTCOME_SOURCE,
  MEASUREMENT_STATUS,
  `extracted::MEASUREMENT_VALUE` AS MEASUREMENT_VALUE_EXTRACTED,
  `extracted::IS_MEASUREMENT_EXTRACTED` AS IS_VALUE_EXTRACTED,
  `extracted::IS_POS` AS OUTCOME_POS_EXTRACTED,
  `extracted::TEST_OUTCOME_TEXT` AS OUTCOME_TEXT_EXTRACTED
    
FROM file({filePathMungedTxtGz:String}, TSVWithNames) kanta_lab_table

  -- Sorting using all columns to make the output deterministic.
 ORDER BY (
   FINNGENID,
   SEX,
   APPROX_EVENT_DATETIME,
   EVENT_AGE,
   OMOP_CONCEPT_ID,
   TEST_NAME,
   TEST_ID,
   TEST_ID_IS_NATIONAL,
   MEASUREMENT_STATUS,
   TEST_OUTCOME_MERGED,
   TEST_OUTCOME_SOURCE,
   MEASUREMENT_VALUE_HARMONIZED,
   MEASUREMENT_UNIT_HARMONIZED,
   MEASUREMENT_VALUE_EXTRACTED,
   IS_VALUE_EXTRACTED,
   OUTCOME_POS_EXTRACTED,
   OUTCOME_TEXT_EXTRACTED

)

-- Deduplicating rows.
 LIMIT 1 BY (
   FINNGENID,
   SEX,
   APPROX_EVENT_DATETIME,
   EVENT_AGE,
   OMOP_CONCEPT_ID,
   TEST_NAME,
   TEST_ID,
   TEST_ID_IS_NATIONAL,
   MEASUREMENT_STATUS,
   TEST_OUTCOME_MERGED,
   TEST_OUTCOME_SOURCE,
   MEASUREMENT_VALUE_HARMONIZED,
   MEASUREMENT_UNIT_HARMONIZED,
   MEASUREMENT_VALUE_EXTRACTED,
   IS_VALUE_EXTRACTED,
   OUTCOME_POS_EXTRACTED,
   OUTCOME_TEXT_EXTRACTED
 )

-- Set output format to TSV-gzipped with a header.
FORMAT TSVWithNames

-- Disable data type inference from TSV text file.
SETTINGS input_format_tsv_use_best_effort_in_schema_inference = 0
